### ISSUE TITLE
Promise超时问题

### ISSUE THREAD

**Issue by YannickXiong** [ShaoNianyr/ppts#1]
⠸ Extracting metrics 1/10{ TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/usr/local/lib/node_modules/ppts/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (/usr/local/lib/node_modules/ppts/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.waitForNavigation (/usr/local/lib/node_modules/ppts/node_modules/puppeteer/lib/Page.js:694:49)
    at Page.<anonymous> (/usr/local/lib/node_modules/ppts/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.reload (/usr/local/lib/node_modules/ppts/node_modules/puppeteer/lib/Page.js:683:12)
    at Page.<anonymous> (/usr/local/lib/node_modules/ppts/node_modules/puppeteer/lib/helper.js:112:23)
    at module.exports (/usr/local/lib/node_modules/ppts/js/runner.js:27:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'TimeoutError' }

**Comment by shaonianyr** [comment]
Fixed, update ppts v1.3.0.
