### ISSUE TITLE
帮忙看下这是怎么回事呀，启动不起来

### ISSUE THREAD

**Issue by Pactortester** [ShaoNianyr/ppts#4]
![image](https://user-images.githubusercontent.com/29191106/102437654-da12e000-4055-11eb-9e81-fd4c1d7c5946.png)

**Comment by Pactortester** [comment]
D:\project\ppts>ppts -r 100 https://www.baidu.com
- Launching Browser(node:11568) UnhandledPromiseRejectionWarning: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (D:\project\ppts\node_modules\puppeteer\lib\Launcher.js:119:15)
    at async start (D:\project\ppts\index.js:56:25)
(node:11568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, o
r by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=stri
ct` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js
 process with a non-zero exit code.
- Launching Browser
